server:
  port: 8080

path:
  include:
    - /admin
    - /portal
    - /user/history
    - /user/addVideo
    - /user/accountSet
    - /user/myVideo
  exclude:
    - /user/loginPage
    - /user/registerPage
    - /

#DataSource配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.70.60.67:3306/videocloud?UseUnicode=true&characterEncoding=utf8&serverTimezone=%2B8
    username: java2205
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 启动热加载
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/*Mapper.xml
  type-aliases-package: com.videocloud.entity
logging:
  level:
    com.videocloud.mapper: debug



#Spring:
#  mail:
#    #smtp服务主机  qq邮箱则为smtp.qq.com
#    host: smtp.163.com
#    #服务协议
#    protocol: smtp
#    # 编码集
#    default-encoding: UTF-8
#    #发送邮件的账户
#    username: 19834090866@163.com
#    #授权码
#    password: DVLZROTEPVGZCTES
#    test-connection: true
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true

