server:
  port: 8080

#DataSource配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.70.60.67:3306/sq_173cms?UseUnicode=true&characterEncoding=utf8&serverTimezone=%2B8
    username: java2205
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 启动热加载
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.videocloud.entity
logging:
  level:
    com.videocloud.mapper: debug
